From 42e3f290ea91f6c95284d9457d2d9261a75b71b7 Mon Sep 17 00:00:00 2001
From: Sean Mackrory <sean@cloudera.com>
Date: Thu, 3 Nov 2016 16:44:14 -0600
Subject: [PATCH 1999/2748] CLOUDERA-BUILD. Backport of HADOOP-13130 needed to
 change exception type in
 TestS3ATemporaryCredentials

Change-Id: If79856a3e8579c22b6c53311b329ad06e6c0a847
---
 .../hadoop/fs/s3a/TestS3ATemporaryCredentials.java |    2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/TestS3ATemporaryCredentials.java b/hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/TestS3ATemporaryCredentials.java
index 303f06c..2d45bcc 100644
--- a/hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/TestS3ATemporaryCredentials.java
+++ b/hadoop-tools/hadoop-aws/src/test/java/org/apache/hadoop/fs/s3a/TestS3ATemporaryCredentials.java
@@ -123,7 +123,7 @@ public void testSTS() throws IOException {
       createAndVerifyFile(fs, path("testSTSInvalidToken"), TEST_FILE_SIZE);
       fail("Expected an access exception, but file access to "
           + fs.getUri() + " was allowed: " + fs);
-    } catch (RuntimeException ex) {
+    } catch (AWSS3IOException ex) {
       LOG.info("Expected Exception: {}", ex.toString());
       LOG.debug("Expected Exception: {}", ex, ex);
     }
-- 
1.7.9.5

